# Generated by Django 3.2 on 2022-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('sub_heading', models.CharField(max_length=50)),
                ('sub_description', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.URLField(default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('image', models.URLField(default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditOurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('image', models.URLField(default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='newPicture/')),
                ('firstDescription', models.CharField(max_length=200)),
                ('secondDescription', models.CharField(max_length=200)),
            ],
        ),
    ]
