# Generated by Django 4.0.4 on 2022-05-04 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=500)),
                ('image', models.URLField(default=None, null=True)),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='members_in_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
