# Generated by Django 3.2 on 2022-04-28 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('maiden_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Select', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address2', models.CharField(default='APT #', max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=20)),
                ('graduate_year', models.CharField(max_length=4)),
                ('couple_with', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couple_with', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
