# Generated by Django 4.0.4 on 2022-05-04 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_eventrsvp'),
        ('accounts', '0002_alter_profile_managers_remove_profile_couple_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.membership'),
        ),
    ]
