# Generated by Django 4.0.4 on 2022-05-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_address2'),
        ('accounts', '0002_alter_profile_managers_remove_profile_couple_with_and_more'),
    ]

    operations = [
    ]
