# Generated by Django 4.0.4 on 2022-05-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_membership'),
        ('accounts', '0004_alter_profile_address2'),
    ]

    operations = [
    ]
