# Generated by Django 4.0.4 on 2022-05-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2500)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.URLField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=500)),
                ('image', models.URLField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=200)),
                ('description', models.TextField(default=True, max_length=500)),
                ('image', models.URLField(default=None, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2500)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50000)),
                ('date', models.DateField()),
                ('image', models.URLField(default=None, null=True)),
            ],
        ),
    ]
