# Generated by Django 4.0.4 on 2022-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_membership_description_alter_membership_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.ManyToManyField(blank=True, null=True, related_name='event_members', to='main.event')),
            ],
        ),
    ]
