# Generated by Django 4.0.4 on 2022-05-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_eventrsvp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRsvp',
        ),
    ]
