# Generated by Django 4.0.4 on 2022-05-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_eventrsvp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
